
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-test

spec:
  selector:
    matchLabels:
      app: vpn-test
  replicas: 1
  template:
    metadata:
      name: vpn-test
      labels:
        app: vpn-test
    spec:
      containers:
      - name: vpn-provider
        image: qmcgaw/gluetun:latest
        imagePullPolicy: Always
        env:
          - name: PERIOD
            value: 1m
          - name: VPNSP
            value: pia
          - name: OPENVPN_USER
            valueFrom:
              secretKeyRef:
                name: pia
                key: username
          - name: PROTOCOL
            value: udp
          - name: OPENVPN_VERBOSITY
            value: "1"
          # name: PIA only
          - name: REGION
            value: "Netherlands"
          - name: OPENVPN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pia
                key: password
          - name: PIA_ENCRYPTION
            value: "strong"
          # DNS over TLS
          - name: DOT
            value: "on"
          - name: DOT_PROVIDERS
            value: "cloudflare"
          - name: DOT_IPV6
            value: "on"
          - name: DOT_VERBOSITY
            value: "1"
          - name: BLOCK_MALICIOUS
            value: "on"
          - name: BLOCK_SURVEILLANCE
            value: "on"
          - name: BLOCK_ADS
            value: "on"
          # name: Port
          - name: PORT_FORWARDING
            value: "off"
          - name: PORT_FORWARDING_STATUS_FILE
            value: "/forwarded_port"
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      - name: test-consumer
        image: linuxserver/jackett
        env:
          - name: PERIOD
            value: "1m"
        step:
          network_mode: test-container